<?php
/**
 * Local Data Export Script for KP-HUB
 *
 * Exports all posts, users, and related data from local database
 */

// Local database configuration
$host = 'localhost';
$dbname = 'kphub';
$username = 'root';
$password = '';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=utf8mb4", $username, $password);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    die("Local database connection failed: " . $e->getMessage());
}

echo "Starting KP-HUB local data export...\n";
echo "=======================================\n\n";

try {
    $exportFile = 'kphub_export.sql';
    $sql = "-- KP-HUB Data Export\n";
    $sql .= "-- Generated on: " . date('Y-m-d H:i:s') . "\n";
    $sql .= "-- DO NOT EDIT THIS FILE\n\n";

    $sql .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";

    // Export users table
    echo "Exporting users...\n";
    $stmt = $pdo->query("SELECT * FROM users ORDER BY user_id");
    $users = $stmt->fetchAll(PDO::FETCH_ASSOC);

    $sql .= "-- Users table\n";
    foreach ($users as $user) {
        $columns = array_keys($user);
        $values = array_map(function($val) use ($pdo) {
            return $val === null ? 'NULL' : $pdo->quote($val);
        }, array_values($user));

        $sql .= "INSERT INTO users (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
    }
    $sql .= "\n";

    // Export posts table
    echo "Exporting posts...\n";
    $stmt = $pdo->query("SELECT * FROM posts ORDER BY post_id");
    $posts = $stmt->fetchAll(PDO::FETCH_ASSOC);

    $sql .= "-- Posts table\n";
    foreach ($posts as $post) {
        $columns = array_keys($post);
        $values = array_map(function($val) use ($pdo) {
            return $val === null ? 'NULL' : $pdo->quote($val);
        }, array_values($post));

        $sql .= "INSERT INTO posts (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
    }
    $sql .= "\n";

    // Export post_reactions table
    echo "Exporting post reactions...\n";
    $stmt = $pdo->query("SELECT * FROM post_reactions ORDER BY reaction_id");
    $reactions = $stmt->fetchAll(PDO::FETCH_ASSOC);

    if (!empty($reactions)) {
        $sql .= "-- Post reactions table\n";
        foreach ($reactions as $reaction) {
            $columns = array_keys($reaction);
            $values = array_map(function($val) use ($pdo) {
                return $val === null ? 'NULL' : $pdo->quote($val);
            }, array_values($reaction));

            $sql .= "INSERT INTO post_reactions (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
        }
        $sql .= "\n";
    }

    // Export file_downloads table
    echo "Exporting file downloads...\n";
    $stmt = $pdo->query("SELECT * FROM file_downloads ORDER BY download_id");
    $downloads = $stmt->fetchAll(PDO::FETCH_ASSOC);

    if (!empty($downloads)) {
        $sql .= "-- File downloads table\n";
        foreach ($downloads as $download) {
            $columns = array_keys($download);
            $values = array_map(function($val) use ($pdo) {
                return $val === null ? 'NULL' : $pdo->quote($val);
            }, array_values($download));

            $sql .= "INSERT INTO file_downloads (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
        }
        $sql .= "\n";
    }

    $sql .= "SET FOREIGN_KEY_CHECKS = 1;\n\n";
    $sql .= "-- Export completed successfully\n";

    // Write to file
    file_put_contents($exportFile, $sql);

    echo "\n✅ Export completed successfully!\n";
    echo "📄 File saved as: $exportFile\n";
    echo "📊 Exported data:\n";
    echo "   - Users: " . count($users) . "\n";
    echo "   - Posts: " . count($posts) . "\n";
    echo "   - Reactions: " . count($reactions) . "\n";
    echo "   - Downloads: " . count($downloads) . "\n";
    echo "\n📤 Upload this file to your Hostinger server and import it via phpMyAdmin\n";

} catch (Exception $e) {
    echo "❌ Export failed: " . $e->getMessage() . "\n";
}
?>